* Borro todos los enlaces de la venta de inicio o sus programas.
      Algunos como spotify son enlaces que al pulsarlos van a la tienda de Windows y lo instalan.
      Otros son realmente programas instalados,
      Los borro o elimino los enlaces.
* Me aseguro que el antivirus está instalado y ejecutándose Cómo???????
* Incorporo el teclado inglés americano
  - voy a opciones -|X|>teclado->americano
  - lo puedeo pasar a esp con tecla windows-SPC
* Ojo voy a trabajar con la aplicación "Terminal" y no con la "PowerShell" directamente. Por las pesatañas básicamente.
* Instalo un WSL (Windows susbsistem Linux)
  - docu de https://www.youtube.com/watch?v=f_CC4GZ0UnY para la instalacion del SO
    	 https://www.youtube.com/watch?v=Do81AMBa0Rk para la app con X
	 https://youtu.be/_Hne4gm8plo corriendo contenedores docker
	 El manual oficial de windows es:
	 https://learn.microsoft.com/es-es/windows/wsl/tutorials/gui-apps
  - Abro una PowerShell, lo elevo con botón derecho sobre el icono del Dock "Run as Administrator"
  y ejecuto el script: src_eshell{wsl --install} y reinicio al acabar de instalar.
  - como insertar código en 
	https://orgmode.org/manual/Structure-of-Code-Blocks.html  
	https://orgmode.org/worg/org-contrib/babel/languages/index.html  
	https://orgmode.org/worg/org-contrib/babel/languages/ob-doc-shell.html 	https://www.gnu.org/software/emacs/manual/html_mono/eshell.html
	
  - Vuelvo al PowerShell como administrador e instalo Ubuntu src_sh{wsl --instal -d ubuntu}
  - en un solo script. Ojo que luego tengo que reniciar la máquina:
#+BEGIN_SRC sh
wsl --install
wsl --install -d ubuntu
#+END_SRC
  - Compruebo que todo funciona con src_sh{wsl --list -v} y con
#+BEGIN_SRC sh
pwd
lsb_release -a
#+END_SRC
* Actualizo el ubuntu
  - Entro con el terminal de Ubuntu y ejecuto src_sh{sudo apt-get update && sudo apt-get upgrade && sudo apt-get update }
  - Entro con el terminal de Ubuntu y ejecuto src_sh{sudo apt-get install git emacs octave nautilus -y}
